* Introduction

Citation Einstein:

#+BEGIN_QUOTE
On ne peut pas résoudre les problèmes avec le même modèle mental qui les a créés. ---Albert Einstein
#+END_QUOTE

Par conséquent, il va falloir penser et agir différemment si l'on veut négocier au mieux la transition forcée que la société thermo-indisutrielle va se voir imposer en conséquence de ses dégats environnementaux et de l'épuisement des ressources qu'elle a causé.

Malheureusement, la population terrestre n'est pas homogène et tout le monde n'a pas le même niveau de développement. Chacun, chaque société, se situe à un niveau de développement correspondant à ce qui lui convient, dans l'environnement où il se trouve (par conséquent il n'y a pas de meilleur niveau qu'un autre). Le modèle utilisé ici est celui de la Spirale Dynamique (rappel: tous les modèles sont faux, mais certains sont utiles).

** L'effondrement à venir

[[https://clubofrome.org/publication/the-limits-to-growth/][Voir 1er rapport au Club de Rome (anglais)]]

** La Spirale Dynamique (SD)

[[https://fr.wikipedia.org/wiki/Spirale_dynamique][Source]]

** IFF World System Model (WSM)

[[https://medium.com/age-of-awareness/the-iff-world-system-model-afa8d700dad9][Source]]

** Les trois horizons (3H)

[[https://medium.com/activate-the-future/the-three-horizons-of-innovation-and-culture-change-d9681b0e0b0f][Source]]

** Le Viable System Model (VSM)

** Team Syntegrity (TS)

** Interactive Planning/Idealized Design (IP/ID)

