* Introduction

Citation Einstein:

#+BEGIN_QUOTE
On ne peut pas résoudre les problèmes avec le même modèle mental qui les a créés. ---Albert Einstein
#+END_QUOTE

Par conséquent, il va falloir penser et agir différemment si l'on veut négocier au mieux la transition forcée que la société thermo-indisutrielle va se voir imposer en conséquence de ses dégats environnementaux et de l'épuisement des ressources qu'elle a causé.

Malheureusement, la population terrestre n'est pas homogène et tout le monde n'a pas le même niveau de développement. Chacun, chaque société, se situe à un niveau de développement correspondant à ce qui lui convient, dans l'environnement où il se trouve (par conséquent il n'y a pas de meilleur niveau qu'un autre). Le modèle utilisé ici est celui de la Spirale Dynamique (rappel: tous les modèles sont faux, mais certains sont utiles).

** Les critères d'une transition réussie

Si la transition sera forcée et non évitable, ses critères de réussite seront :
- limiter les dégats sans retarder l'échéance (car l'impact serait plus important)
- arriver à vivre dans un monde réchauffé, post-carbone/pétrole/éléments rares
- construire une vie, une société humaine, avec l'impact environnemental le plus faible possible (surface terrestre utilisée la plus faible possible, toutes activités confondues)

** L'effondrement à venir

[[https://clubofrome.org/publication/the-limits-to-growth/][Voir 1er rapport au Club de Rome (anglais)]]

** TODO La Spirale Dynamique (SD)

[[https://fr.wikipedia.org/wiki/Spirale_dynamique][Source]]

*** Explication rapide du modèle
*** Niveau différent = compréhension différente de la situation = Solutions différentes
*** Présenter les intérêts à changer différemment à chaque niveau
*** Il faut du Jaune au moins pour coordonner le tout (jongler avec les différents niveaux) et une méthode (Jaune) peut aider

#+INCLUDE: "./spirale_dynamique.org"

** IFF World System Model (WSM)

[[https://medium.com/age-of-awareness/the-iff-world-system-model-afa8d700dad9][Source]]

#+BEGIN_QUOTE
    The World System Model establishes a holistic structure for visioning the state of the world and, thereby, a platform for understanding our global predicament, assessing innovations and designing wise initiatives.

    --- Anthony Hodgson (2011: 43)
#+END_QUOTE

*** Un modèle "complet" de tous les domaines de la société humaine qu'il faudrait repenser à l'aune de la Transition:
1. Valeurs culturelles et vision du monde
2. Santé et bien-être
3. Nourriture et agriculture
4. Affaires et commerce
5. Energie et ressources naturelles
6. Intensité du changement climatique
7. Fonctions écosystémiques
8. Disponibilité de l'eau 
9. Habitat et infrastructures
10. Economie et richesse
11. Gouvernance et institutions
12. Communautés

*** Les 12 domaines doivent être traités selon les 3 horizons et en relation systémique les uns avec les autres (Team Syntegrity)

** Les trois horizons (3H)

[[https://medium.com/activate-the-future/the-three-horizons-of-innovation-and-culture-change-d9681b0e0b0f][Source]]

*** H1: la vie actuelle et les éléments qu'il convient d'arrêter (ou qui vont devoir s'arrêter faute de ressources)
*** H2: ce qu'il faut préparer pour l'avenir (avec les ressources libérées en H1)
*** H3: ce qu'il faudra construire pour que l'on puisse vivre demain

** Team Syntegrity (TS)

*** Méthode générale pour organiser les interactions systémique entre tous les domaines du WSM

** Interactive Planning/Idealized Design (IP/ID)

[[https://eaasos.info/Content/Downloads/AckoffGuidetoIdealizedRedesign.pdf][Source]]

*** Méthode pour planifier le détail de ce qu'il faut faire aux 3 horizons
*** Idéalisation
**** Formuler le problème
**** Planifier la cible
*** Réalisation
**** Planifier les moyens
**** Planifier les ressources
**** Concevoir l'implémentation
**** Concevoir les contrôles
*** Design idéalisé
**** Mission
**** Spécification et design


** Le Viable System Model (VSM)
[[https://en.wikipedia.org/wiki/Viable_system_model][Wikipedia anglais]]

Méthode pour déléguer le fonctionnement localiser, mais tout de même permettre la synchronisation des domaines ou biorégions les unes avec les autres.
